---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/chat_applications":
    get:
      summary: Returns all applications
      tags:
      - Chat Applications
      responses:
        '200':
          description: Successfull
          content:
            application/json:
              example:
              - token: xsad43a2awd
                name: test_name
              - token: hfdg44234d
                name: test_name_2
    post:
      summary: Creates a chat application
      tags:
      - Chat Applications
      parameters: []
      responses:
        '201':
          description: Chat Application Created
        '401':
          description: Unprocessable Entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/chat_applications/{token}":
    get:
      summary: Retreives a chat application
      tags:
      - Chat Applications
      parameters:
      - name: token
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Chat Application Found
          content:
            application/json:
              example:
                token: 231gasjJsda
                name: test_name
        '404':
          description: Chat Application Not Found
          content:
            application/json:
              example:
                token: 231gasjJsda
                name: test_name
    patch:
      summary: Updates existing Chat Application
      tags:
      - Chat Applications
      parameters:
      - name: token
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully updated
        '422':
          description: Unprocessable Entity
        '404':
          description: Chat Application Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/chat_applications/{chat_application_token}/chats":
    get:
      summary: Retrieves all chats belonging to a specific application
      tags:
      - Chats
      parameters:
      - name: chat_application_token
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Get chats
          content:
            application/json:
              example:
              - number: 1
              - number: 2
    post:
      summary: Creates a new chat
      tags:
      - Chats
      parameters:
      - name: chat_application_token
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Successfully created
        '400':
          description: Bad Request
